# Giải đống 1: Lấy image cơ sở Node.js từ node:18-alpine
FROM node:20-alpine

# Thiết lập thư mục làm việc bên trong container
WORKDIR /app

# Sao chép package.json và package-lock.json vào TRƯỚC
COPY client/package*.json ./

# Lệnh RUN npm install chỉ chạy nếu file nào thay đổi.
RUN npm install

# Sao chép phần còn lại của client
COPY client/ ./

# Mặc định, React dev server sẽ chạy trên cổng 3000.
# Thiết lập biến môi trường để nó chạy trên cổng này.
ENV HOST=0.0.0.0

# Thông báo rằng container sẽ lắng nghe trên cổng 3000
EXPOSE 3000

# Lệnh mặc định để khởi chạy container
CMD ["npm", "start"]