version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app       # bind mount để sửa code auto update
      - /app/node_modules   # tránh ghi đè node_modules trong container
    environment:
      - CHOKIDAR_USEPOLLING=true  # fix hot reload trong container
