# Dùng NodeJS base image
FROM node:20-alpine

# Tạo thư mục làm việc
WORKDIR /app

# Copy package.json trước
COPY client/package*.json ./

# Cài dependency
RUN npm install

# Copy code (nếu build production thì giữ, dev thì có thể bỏ để bind mount)
# COPY client/ ./
COPY . ./   # vì context chính là /var/www/project/client

# React dev server listen mọi IP
ENV HOST=0.0.0.0
EXPOSE 3000

# Chạy server
CMD ["npm", "start"]
